#!/usr/bin/env bash
# Install the git pre-push hook for the `poli-page` Rust SDK.
# Spec §16.4 — idempotent; safe to re-run after a clone or upgrade.
#
# The installed hook runs `cargo fmt --check`, `cargo clippy -D warnings`,
# and `cargo test --all-features` on every push. Integration tests are
# skipped by default; opt in with:
#
#     RUN_INTEGRATION=1 git push
#

set -euo pipefail

cd "$(dirname "$0")/.."

GIT_DIR=$(git rev-parse --git-dir)
HOOK_PATH="$GIT_DIR/hooks/pre-push"

cat > "$HOOK_PATH" <<'HOOK'
#!/usr/bin/env bash
# Generated by scripts/install-hooks.sh — re-run that script to refresh.
set -euo pipefail

repo_root=$(git rev-parse --show-toplevel)
cd "$repo_root"

printf "\033[36m→\033[0m cargo fmt --all --check\n"
cargo fmt --all --check

printf "\033[36m→\033[0m cargo clippy --all-targets --all-features -- -D warnings\n"
cargo clippy --all-targets --all-features --locked -- -D warnings

printf "\033[36m→\033[0m cargo test --all-features\n"
cargo test --all-features --locked

if [[ "${RUN_INTEGRATION:-0}" == "1" ]]; then
    if [[ -z "${POLI_PAGE_API_KEY:-}" ]]; then
        printf "\033[33m⚠ RUN_INTEGRATION=1 but POLI_PAGE_API_KEY not set — skipping integration tests\033[0m\n"
    else
        printf "\033[36m→\033[0m cargo test --features integration --test integration -- --ignored\n"
        cargo test --features integration --test integration -- --ignored
    fi
fi

printf "\033[32m✓ pre-push checks passed\033[0m\n"
HOOK

chmod +x "$HOOK_PATH"

printf "\033[32m✓\033[0m Installed pre-push hook at %s\n" "$HOOK_PATH"
printf "  Skip with: \033[2mgit push --no-verify\033[0m\n"
printf "  Include integration tests: \033[2mRUN_INTEGRATION=1 git push\033[0m\n"
